fix pre-commit hook script

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -23,8 +23,7 @@ if [ -n "$STAGED_UTILS" ]; then
     echo "Running tests for changed utils files:"
     echo "${STAGED_UTILS/^/  - }"
 
-    echo "$STAGED_UTILS" | xargs -P 0 -I {} python3 {}
-    if [ $? -ne 0 ]; then
+    if ! (echo "$STAGED_UTILS" | xargs -P 0 -I {} python3 {}); then
         echo "❌ One or more tests in utils/ failed."
         FAILED=1
     else
@@ -49,17 +48,20 @@ if [ -n "$STAGED_TARGETS" ]; then
         for STAGED_TARGET in ${STAGED_TARGETS}; do
             test_dirs_to_run+=$(basename "$(dirname "${STAGED_TARGET}")")" "
         done
+        # Removing the lone tailing space at the end.
+        test_dirs_to_run="${test_dirs_to_run% }"
+        # Convert space-separated list to line-separated one.
         test_dirs_to_run=$(echo "${test_dirs_to_run}" | tr -s ' ' '\n' | sort | uniq | tr -s '\n' ' ')
+        # Removing the lone tailing space at the end.
+        test_dirs_to_run="${test_dirs_to_run% }"
     fi
     if [ -f "${UNSORTED_DIR}/run_all.sh" ]; then
-        echo "Changes detected in utils/ or unsorted/. Executing run_all.sh..."
-
+        echo "Changes detected in utils/ or unsorted/. Executing run_all.sh with argument \"${test_dirs_to_run}\" ..."
         # Execute run_all.sh inside its native directory using a subshell
-        (
-            cd "$UNSORTED_DIR" || exit 1
+        if ! (
+            cd "$UNSORTED_DIR" || (>&2 echo "failed to cd to \"$UNSORTED_DIR\"" && exit 1)
             bash ./run_all.sh "${test_dirs_to_run}"
-        )
-        if [ $? -ne 0 ]; then
+        ); then
             echo "❌ Script run_all.sh failed."
             FAILED=1
         else
